### ISSUE TITLE
Fireworks causing damage to players

### ISSUE THREAD

**Issue by VerumUK** [PyvesB/AdvancedAchievements#136]
Hey there,
When getting an achievement the fireworks seem to be causing damage to players who are in survival, this can effectively kill someone who may be on low hp. It doesn't seem to cause damage 100% of the time, I had to get a few achievements for the gif posted below before it did damage but does happen.

aach version: 4.1.3
Server version: 1.11.2

Proof: https://i.gyazo.com/ff7aae4b8e08fc4493a370feae2ffd25.gif

Seen this reported multiple times in the plugin discussion page but no one reported it here so thought I'd do it, thanks in advance.

**Comment by Platinteufel** [comment]
Are you running WorldGuard? The latest dev-builds include options to prevent firework damage as this is a default feature in Minecraft 1.11.

**Comment by VerumUK** [comment]
Yes I am using Worldguard, do you happen to know which version implemented the firework damage prevention? I see some issues with the latest version of worldguard so I've been putting off updating mine.

**Comment by Platinteufel** [comment]
Seems like 1699 implements them. 
http://builds.enginehub.org/job/worldguard?branch=master

**Comment by PyvesB** [comment]
Hello,

The firework damage occurs since Minecraft 1.11.2, in general when you have obstacles above your head preventing the firework from flying high enough. Unfortunately there doesn't seem to be any trivial fix to prevent this behaviour (at least I don't know any). I will have to implement a more complex workaround, and will try to release it as soon as possible.

Cheers,

Pyves
