### ISSUE TITLE
Problem with Config 

### ISSUE THREAD

**Issue by Hakuati** [PyvesB/AdvancedAchievements#15]
Hey Developer!

I have in the config few achivments added 
but if the are drinne then it works no longer
plugin can be at the Config times 
nd see what I did wrong ??

Sry for my English! I am Germany!

[http://www.mediafire.com/download/v4t1qlm7wk42mvq/config.yml](url)

Mfg

**Comment by PyvesB** [comment]
Hello,

You forgot a closing apostrophe line 378 in the configuration file. Also, when you don't wish to put any achievements for a given category, I recommend using [] instead of the white space.

Here's the corrected configuration file: https://gist.github.com/PyvesB/02d149782c28b556b3af

Another tip: as stated at the beginning of the config file, you should use yaml-online-parser.appspot.com to make sure your YAML files are correct. ;-)

Cheers,

Pyves

**Comment by Hakuati** [comment]
I have the file konfiguierte
but now replaced now makes the
 plugin nothing more can no longer reload nothing ..

Mfg

**Comment by PyvesB** [comment]
What are the errors shown in the console? There still must be a problem with the configuration file. ;-)

**Comment by Hakuati** [comment]
Since just stood the no command available .. I've added in the config file no things ...

**Comment by Hakuati** [comment]
No error in this Console..

**Comment by Hakuati** [comment]
I have Error Found :

ERROR:

while parsing a block mapping
  in "<unicode string>", line 358, column 3:
      '1':
      ^
expected <block end>, but found '<scalar>'
  in "<unicode string>", line 382, column 4:
      '10':
       ^

What is this error?

**Comment by PyvesB** [comment]
Apparently there are still errors in the configuration file. Please refer to my message above for advice. Also I just noticed that you had deleted several entire sections in the configuration file you showed me above, you can't expect a plugin to work if you just take out random parts of the config. ;-)

**Comment by Hakuati** [comment]
Now I have the milk with the lanes makes or .. with " # " is provided , it can now be closed Thanks for the help ..

**Comment by PyvesB** [comment]
No problem. Feel free to star the project if you wish. ;-)
