### ISSUE TITLE
Question about break/place/kill/craft achievements.

### ISSUE THREAD

**Issue by Corcustos** [PyvesB/AdvancedAchievements#154]
I'm sorry if this is blantly obvious, but I can't find something that tells me how to do this anywhere. I'm trying to make a global achievement for breaking blocks, placing blocks, kill monsters, and crafting items. I don't want it excluded to just one specific item. For example, I want all block breaks to count towards the achievement, and not just sand/stone etc. I'm not sure what the parameter would be. I've tried all, any, and *, but none of those worked so I'm at a loss. I'm absolutely positive that I'm missing this and overlooked something. It's highly unlikely that it's nonexistent. If someone could point me in the right direction that'd be great. Thanks.

**Comment by PyvesB** [comment]
Hello,

Actually this is not currently possible. The four categories you have listed must be used with a sub-category. Some similar ideas were given in #92, but this has yet to be done.

Cheers,

Pyves

**Comment by Corcustos** [comment]
Why wasn't this ever a feature? It seems like something so fundamental for a plugin like this that it should've been implemented from the start. Any idea when this will happen? It's halting progress of my server and is extremely inconvenient.

**Comment by PyvesB** [comment]
You are (again) complaining about an open-source project because you assume a niche feature you specifically want is not supported. In that case, please feel free to implement it and open a pull request, instead of dismissively and non constructively stating how other people _should have_ done their work.

**Comment by Corcustos** [comment]
It seems that what I said was slightly misunderstood as being aggressive or rude. I apologize if this was the case. I was simply wondering why this wasn't a feature, and if/when it will happen. May I ask why you won't implement this, and why this is invalid despite the fact that it's an actual issue? Thank you for your time and understanding.

**Comment by PyvesB** [comment]
Apologies accepted. ;-)

**Why was it not initially implemented?**
For historical reasons. Advanced Achievements was launched as a project aimed at fixing [Achievement](https://github.com/deathmarine/Achievement). Breaks, Kills, Places and Crafts are the four only categories that existed in that plugin, that's how they worked as you can see in the [config file](https://github.com/deathmarine/Achievement/blob/master/config.yml).

**Why hasn't it been implemented since?**
- Rarely asked feature.
- "all" as a global statistic counting just the action?
  - Statistic not currently tracked. If added, current users will end up with discrepancies such us "broken sand equal to 113 but total blocks broken equal to 0".
- "all" as a sum of the statistics for all specified sub-categories?
  - Also, complicated to integrate in existing installation of the plugins, because of what is discussed in question 4 of the FAQ.
  - Heavier database queries. For these categories, looking for one tuple in a database table is fast, looking for several and summing them up to get a global statistic is less efficient.
- Not really challenging from a developer's point of view.

I've left #92 as there are some similar ideas, maybe another dev or myself will pick it up at some point!

**Comment by Corcustos** [comment]
Ah, that makes more sense. Thank you for clarifying! I'm able to work around it just fine so it's all good now. Your assistance is much appreciated.
