### ISSUE TITLE
Config.yml Has No Achievements 

### ISSUE THREAD

**Issue by CopperGenie** [PyvesB/AdvancedAchievements#16]
When I use the plugin without editing the config.yml, the plugin works normally, but when I added achievements to the config.yml, the file deletes ALL of the achievements and just has the basic config options. 

(I converted the .yml files to .txt files to upload.)

[config.txt](https://github.com/PyvesB/AdvancedAchievements/files/200891/config.txt)
[config2.txt](https://github.com/PyvesB/AdvancedAchievements/files/200892/config2.txt)

(config.txt is the edited config.yml file, and config2.txt is the edited config.yml file after loading the server (i.e. after the achievements get deleted).

**Comment by CopperGenie** [comment]
config.txt is the edited config.yml file, and config2.txt is the edited config.yml file after loading the server (i.e. after the achievements get deleted).

**Comment by PyvesB** [comment]
Hello,

You used same tabs instead of spaces in the configuration file, this is not allowed in YAML. Here is the corrected version:
https://gist.github.com/PyvesB/462775161c45714501b7ce4faf97d0c0

Don't forget to use yaml-online-parser.appspot.com to check the syntax of your YAML files. ;-)

By the way, a new version of the plugin is on its way, version 2.4.4, I recommend upgrading from version 2.4.3.

Cheers,

Pyves

**Comment by PyvesB** [comment]
I'm assuming you solved your problem, as it has been more than one week, so I'll close this issue.

Cheers,

Pyves
