### ISSUE TITLE
Category issue

### ISSUE THREAD

**Issue by test123account** [PyvesB/AdvancedAchievements#166]
I can not find option to make all achievements display on ' /aach list ' without having to use separate category?

Example: when player does ' /aach list ' it will show all achievements and progress not the categories

If not a feature can you add it please

**Comment by PyvesB** [comment]
Hello,

The plugin is based on categories, and that's how the achievements are set up in the GUI. I don't see the point in wanting to do otherwise, as it would be ridiculously messy to chuck all the achievements together, would require GUI pagination, and would come with a significant performance hit when running the /aach list command. Unfortunately I'm afraid this will not be done. ;-)

Cheers,

Pyves

**Comment by test123account** [comment]
Ok :(
