### ISSUE TITLE
Bug : /aa stats do not count everything

### ISSUE THREAD

**Issue by aurel85** [PyvesB/AdvancedAchievements#179]
Hey,

On my server I have a dozen success that have as a reward a command. But I just noticed that in the /aa stats (therefore also /aa top and others) these success are not counted.
For example the /aa stats tells me 208/245 while if I count one by one in the /aa list I miss 29 success.
By making a small calculation the difference is 8 (245 - 208 = 37; 37 - 29 = 8)

And 8 corresponds to the number of success that I won with a command at its end. I was able to check this on at least one other player who had a difference of 9 and he had won 9 success that made an order.

Note that all other success give money.

I looked in the config I did not see anything special so I think there is a small bug somewhere. Thank you in advance.

_I use PaperSpigot 1.11.2 (1090) and the latest version of the plugin (5.0.3)._

**Comment by PyvesB** [comment]
Hello,

This is strange behaviour, I will look into it. ;-)

Cheers,

Pyves

**Comment by PyvesB** [comment]
I have not been able to reproduce this problem Could you please show me your full configuration?

**Comment by aurel85** [comment]
Yes I send it to you by mp on spigot, and a few days ago I won a success that rewarded me with an order and it was counted, so I do not understand too much in what condition a success does Not included in the /aa stats.

**Comment by PyvesB** [comment]
I have spotted several problems within your configuration.

The _Name_ parameters you have used are not unique. For instance the achievements in the _ConsumedPotions_ and _Brewing_ categories are the same. Same goes for some of the _Bed_ achievements, and probably others I haven't spotted. 

_Name_ is used as the database key. /aach list checks all keys individually and displays the achievement as being received if it finds the key. On the other hand, /aach stats counts the number of different keys, that's why it displays less achievements than /aach list.

Unfortunately you are not going to be able to fix this in a clean manner, unless you're comfortable with SQL. Indeed, for instance if a player has received achievement _potion1_, there is no easy way to tell whether the player actually received "&6Jeu dangereux" or "&6Première fois" or both. The only solution would be to go in the corresponding statistics database tables and repopulate the main _achievements_ table correctly. You could probably come up with SQL queries to do this quite quickly.

**Comment by aurel85** [comment]
I should have read my config better...
Anyway, thanks for the help and I'll look at it all from my side.

**Comment by PyvesB** [comment]
Okay, feel free to reopen the issue if you need any help on how to proceed.
