### ISSUE TITLE
Bug : Achievement Brewing is broken

### ISSUE THREAD

**Issue by aurel85** [PyvesB/AdvancedAchievements#191]
Hi,

When players prepare potions, nothing happens, no matter what potions.

I do not know if it is related to the issue here : #172 
Or if this bug is only present on my server because I changed the configuration the other day (see #179) but I find it strange that only this achievement works anymore.

I use Paper Spigot 1.11.2 and the last version of the plugin (5.1).

Thank you in advance.

**Comment by PyvesB** [comment]
Hello,

Thanks for the report, I will look into it.

Cheers,

Pyves

**Comment by PyvesB** [comment]
You were right, this bug was introduced when I was working on #172. At the time, I was testing on Minecraft 1.8 locally, and everything was fine. But I had completely forgotten that potion handling had changed in Minecraft 1.9. This new implementation should hopefully work across the full spectrum of supported versions, from 1.7.9 to 1.11.2. ;-)
