### ISSUE TITLE
Players are not getting the achievement?

### ISSUE THREAD

**Issue by AndGK** [PyvesB/AdvancedAchievements#205]
A lot of my players complain that they have, for example, gained 150 level when the achievement was for 100 and they do not get a reward. So in the /aach list, it states as 150/100. Is this a bug?
Latest 1.11.2 spigot, and latest aach version.

**Comment by PyvesB** [comment]
Hello,

I am not able to reproduce this problem. You must gain a level for the achievement to be triggered, maybe your players had 150 levels when you added the achievement and have since then not gained any additional levels? Also verify that players have the `achievement.count.maxlevel` permission. ;-)

Cheers,

Pyves
