### ISSUE TITLE
Config mess up on startup

### ISSUE THREAD

**Issue by Platinteufel** [PyvesB/AdvancedAchievements#218]
Hey @PyvesB :)

Since I've updated to the latest version of aach my config get messed up after every startup, see https://pastebin.com/6n2bwhrg. Any idea what could be the problem here? :/

Cheers ;-)

**Comment by PyvesB** [comment]
Hello Platinteufel, 

Try deleting line number 5. ;-) 

Cheers, 

Pyves

**Comment by Platinteufel** [comment]
I just managed to fix it.

The plugin generated 3 options in _"Parameters in future plugin versions will  appear here"_ ..

# When a player gives a pet to another player (requires
# PetMaster plugin version 1.3 or above).
PetMasterGive: {}

# When a player receives a pet from another player (requires
# PetMaster plugin version 1.3 or above).
PetMasterReceive: {}

# When a player enters a specific command (specify command
# prefixes in lower case without spaces).
PlayerCommands: {}

.. because I disabled those categories. That messes up the config completly. I will do some tests soon if I can reproduce it again. :)

**Comment by Platinteufel** [comment]
I was just able to reproduce it:
https://youtu.be/-fJuZzmIxpk

I can provide my config if you want to test it on your own. :)

**Comment by PyvesB** [comment]
Yes, I would definitely appreciate your configuration. ;-)

**Comment by Platinteufel** [comment]
I'll sent it to you via message on SpigotMC :)

**Comment by PyvesB** [comment]
Hello,

The problem didn't come from an Advanced Achievements update, but from recent versions of Spigot. I updated my very hackish workarounds to prevent comments from disappearing when inserting new values into the _.yml_ files. The files should no longer be messed up now. Ideally I should move over to a more robust YAML parsing library, rather than using the buggy/long abandoned CraftBukkit one, but that's a lot of work and probably not worth the effort. ;-)

Cheers,

Pyves

**Comment by Platinteufel** [comment]
Thanks a lot for the workaround, even though it was a very special case. Just wanted to prevent messed up configs for other users, because I was very confused what's wrong.
