### ISSUE TITLE
Adding and destroying

### ISSUE THREAD

**Issue by Blackdigits** [PyvesB/AdvancedAchievements#280]
People would just add and break diamond_ore to get the achievement of #break, is this intentional? Or is there any way to prevent it?

**Comment by PyvesB** [comment]
Hello @Blackdigits,

The `Breaks` category is triggered _"when a specific block is broken"_, so yes, this is intentional, the plugin is doing its job. Nevertheless you can alter the expected behaviour by modifying the `DisableSilkTouchBreaks` or `DisableSilkTouchOreBreaks` configuration options. 😉 

Cheers,

Pyves

**Comment by Blackdigits** [comment]
How about spawners? Can I disable mobkill counts from mobs?

**Comment by PyvesB** [comment]
No, you can't, it wouldn't really make sense. ^^
