### ISSUE TITLE
Custom category help!

### ISSUE THREAD

**Issue by SnUncle** [PyvesB/AdvancedAchievements#310]
Im using default config.yml but when i type /aach add 1 votes player 
sever answer me ' the category votes does not exist'
am i typed the wrong command?

sorry for my bad English

**Comment by PyvesB** [comment]
Hello @SnUncle ,

As shown in the [Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki/Commands-and-permissions) example, you have to specify the category name, for instance ` /aach add 1 Custom.votes player`. You've got auto-completion available, you can just press the _Tab_ key instead of having to type. 😉 

Hope this helps!

Pyves

**Comment by SnUncle** [comment]
thx a lot!
