### ISSUE TITLE
Aach generate error

### ISSUE THREAD

**Issue by coolnickname** [PyvesB/AdvancedAchievements#405]
I know there already is #281 but the paste of the original error was removed so I'm not sure if it's the same issue.

The error I get when running the command as an OP is https://pastebin.com/NDMJP8pe. The error I get when running the command from the console is https://pastebin.com/PjGWVJkk. 
Please note that the error when running from the console is actually a warning but still has no effect.

I'm running Paper version git-Paper-78 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT) with version 5.9.0 of advancedachievements. This was tested with a clean config and I am behind a Waterfall proxy, I guess that could cause some packet issues? 

Also ProtocolSupport 4.29-dev.

**Comment by coolnickname** [comment]
Java 8 on Ubuntu Linux 18.04.1 x64 btw

**Comment by PyvesB** [comment]
Hello @coolnickname ,

The JSON structure of advancements seems to have slightly changed in Minecraft 1.13, causing this issue. I'll look into it. 😉 

Cheers,

Pyves

**Comment by PyvesB** [comment]
Here's a test version that should work with Minecraft 1.13:
[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/2264259/AdvancedAchievements.zip)

Nevertheless, I can't get the background to work at this point. I can't seem to find proper values for `AdvancementsBackground`. If someone has any ideas, feel free to give me a shout, otherwise I'll dig in some more later this week!

**Comment by PyvesB** [comment]
Final version, tested successfully in Minecraft 1.12 and 1.13: [AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/2268123/AdvancedAchievements.zip)

Feel free to ping me if you encounter any new issues!
