### ISSUE TITLE
MySQL: Data too long for column 'mobname'

### ISSUE THREAD

**Issue by eightbitx** [PyvesB/AdvancedAchievements#427]
Getting this error when people complete the **breeding** challenge. This is due to me having multiple mobs listed in the challenge.

Error: https://pastebin.com/tvJy8PhN
My mobname field: `cow|sheep|chicken|pig|horse|ocelot|wolf|parrot|mooshroom|rabbit|llama|turtle`
Solution (for me): Change mobname column length/value to varchar(100)

AACH version: 5.9.3
Server version: Paper 1.13.1

**Comment by eightbitx** [comment]
@PyvesB Is there a way to specify "all mobs"? I don't care what people are breeding, I want it all to be counted.

**Comment by PyvesB** [comment]
@eightbitx I believe that it's not currently possible to do so.

**Comment by PyvesB** [comment]
The issue has been fixed in the above commit. I have attached a development build so you can try it out. The plugin will perform all necessary upgrades automatically. I've tested it successfully with my PostgreSQL database, but just to be on the safe side I do recommend doing a backup before using this version. 👍 

[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/2409149/AdvancedAchievements.zip)
