### ISSUE TITLE
Player Death Reasons

### ISSUE THREAD

**Issue by doitliketyler** [PyvesB/AdvancedAchievements#428]
Hey there. Is there a way to specify the reason for a players death like starvation or wither potion effect? If not could you add this? Thanks in advance.

**Comment by PyvesB** [comment]
Hello @doitliketyler,

There is currently no way to specify the reason for player deaths. This is unlikely to be added, as it would require a migration of the database schema for that category, a reset of relevant statistics and achievements, as well as breaking changes to the configuration file.

Cheers,

Pyves

**Comment by doitliketyler** [comment]
OK then how about adding a new category and capturing the last cause of damage before a player dies and using that?

**Comment by PyvesB** [comment]
I'm reluctant to having two categories cover the same achievement action. This will lead to code and data duplication as well as confusion for the users.

**Comment by doitliketyler** [comment]
Your reason for reluctance is not a good reason to deprive a user from a useful feature and how does this cause confusion for users if the category specifically tells you what its for?

**Comment by PyvesB** [comment]
Depriving users from a feature? This is a pretty dramatic way to put things for something that has been requested for the first time since the plugin was launched in 2015, at least as far as I recall. And yes it is an excellent reason, project maintainers are the ones who bear the cost of code complexity and technical debt, they are entitled not to be enthusiastic about a feature request if they think there will be little benefit for the project.

As you seem to have taken quite an unfriendly and un-constructive stance here, I suggest the following compromise: you can work on this feature request, and submit a pull request once you're done. The [Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki/Developers#modifying-the-plugin) and [contributing guide](https://github.com/PyvesB/AdvancedAchievements/blob/master/CONTRIBUTING.md) will help you get going. I'll then happily review the contribution and we can then discuss the best way of documenting it and ensuring a good user experience. 😉

**Comment by doitliketyler** [comment]
Hmm...so me simply disagreeing with you and asking you how it causes confusion makes me dramatic, unfriendly and un-constructive? Thats interesting.

**Comment by PyvesB** [comment]
Over two months without any news, therefore closing the issue.
