### ISSUE TITLE
Discord 

### ISSUE THREAD

**Issue by Sprungente** [PyvesB/AdvancedAchievements#441]
Add a discordserver for all your plugins. 

:)

**Comment by PyvesB** [comment]
Hey @Sprungente ,

Thanks for your suggestion. I'm in two minds here.

On the one hand Discord is quite trendy at the moment and can help build stronger communities. Looking at what @Rsl1122 has done on his side, I think it's a great setup.

On the other hand, I've been trying to centralise support around GitHub in recent months. Previously people would just keep on finding new ways to contact me. The least that can be said it that is was very chaotic: GitHub issues, personal emails, PMs on either Spigot or Bukkit, profile posts on Spigot, forum posts on Spigot, comments on Bukkit, Spigot reviews, comments on CurseForge, some would even come to find me directly on the server I used to actively administrate at the time... GitHub is a great way to easily keep track of what is outstanding and what needs to be worked on and allows to do fancy things such as linking issues and commits. You can efficiently search for present or past issues and the whole Wiki is accessible in one click on top of each page. I've got a feeling that Discord would be a lazy way for users to get support, they would be more inclined to just dump their problems or questions without reading the Wiki nor going through what has been answered in the past, as it's not convenient to do so with it. That's pretty much what happens on the Spigot plugin thread today and is why I tend to ignore it most of the time.

Another question would be how can we improve the current support offering on GitHub rather than creating a new support channel?

**Comment by Rsl1122** [comment]
I would argue against having a discord if goal is to centralize support to GitHub - you will get PMs if you don't make it clear that you don't want discord PMs. (Good discord server structure can mitigate this, but it's still going to be an issue.) - Disabling direct PMs does not work as that will lead to a lot of friend requests.

I often find that people report exceptions on discord anyway, leading to more work for issue management or forgetting to fix something. It's still an improvement over spigot forums, as you will be able to know if the user gave up before receiving a response.

It's good if your plugin needs different setup steps depending on the setup environment, but for plugins that work out of the box it is unnecessary work.

**Comment by Sprungente** [comment]
I saw at the towny-Discordserver that people telling about how they use this plugin and give ideas how people can use it, but from Developerside it gives no support on the discord. If people ask for support, they  wanna give them a rank. Everyone knows then that this guy don't use he's brain xD in my opinion it is funny  way to handle this

**Comment by PyvesB** [comment]
Based on @Rsl1122, I think I'll be skipping the Discord server for now. Thanks for the suggestion though! 😉
