### ISSUE TITLE
Error with 5.11.0

### ISSUE THREAD

**Issue by aurel85** [PyvesB/AdvancedAchievements#469]
Hi,

With version 5.11.0 of this plugin I have this error that appears without explanation, without anything special being done : https://pastebin.com/K47vE2YV

I use PaperSpigot 1.13.2

**Comment by PyvesB** [comment]
Hello @aurel85,

Did this error start appearing when switching to Advanced Achievements 5.11.0? Or it this just happening in the latest version of Paper? I haven't changed anything other than database code in 5.11.0, so I would be surprised if something unrelated had been broken.

Cheers,

Pyves

**Comment by aurel85** [comment]
The error appeared this afternoon after updating the 460 version of Paper and the latest snapshot version of WorldEdit in my test server. I upgraded AdvancedAchievement yesterday and there was not this problem.

**Comment by eightbitx** [comment]
I'm getting the same error: https://pastebin.com/qWvMALTA. I'm on the Paper Discord and it sounds like build 460 of Paper merged some Spigot changes that changed how the consumer is passed. Z750 says Spigot has since released another update that looks like it should fix this, he is pulling it now for Paper.

**Comment by aurel85** [comment]
With Paper 461 the error is not anymore present.
