### ISSUE TITLE
AdvancedAchievements 1.14 Version?

### ISSUE THREAD

**Issue by Blueeyestar** [PyvesB/AdvancedAchievements#519]
Is there already any information if AdvancedAchievements will be in 1.14 soon?

**Comment by PyvesB** [comment]
Hello @Blueeyestar,

As you will probably have seen on the repository's homepage or the commit history, Minecraft 1.14 support is well underway. Rather than dumping quite an unfriendly and unhelpful issue, why not contribute code, offer help for testing or simply support the project (e.g. star the repo, donate, rate the plugin, etc.) instead? 😉 

Cheers,

Pyves
