### ISSUE TITLE
Can't get advancement background to work

### ISSUE THREAD

**Issue by s1h4d0w** [PyvesB/AdvancedAchievements#578]
I've just set up Advanced Achievements on my server and spent the day adding almost 200 achievements. However I can't get the background for the Advancements/L menu to work, it always says `[AdvancedAchievements] Failed to get internal item name for advancement icon. Using book instead.`, but then ingame the background is the purple/black missing texture image.

We're on Paper 1.14.4 and I'm assuming it has something to do with the format being changed. I first set my AdvancementsBackground to `minecraft:textures/blocks/sand.png` before finding out that "blocks" is now just "block", but it still says it can't find the texture, so it'll use the book one but then shows the missing texture image ingame.

**MC version:** Paper version git-Paper-176 (MC: 1.14.4)
**AA version:** 5.12.4

**Comment by PyvesB** [comment]
Hello @s1h4d0w,

Does the default `minecraft:textures/item/book.png` work at all for you?

Cheers,

Pyves

**Comment by s1h4d0w** [comment]
It doesn't sadly, it still shows the error and uses the purple/black checkered background.

**Comment by PyvesB** [comment]
Hmmm, I just tried with the latest Spigot and you're right, I'm getting the same error. They must have changed the path of textures _again_. This will need some more investigation, but do let me know if you find anything useful!

**Comment by s1h4d0w** [comment]
What I can add is that I downloaded a random 1.14 texture pack to look at the file structure, and it seemed to be the same aside of the folders now being singular instead of plural, so "blocks" changed to "block", "items" is now "item", etc. But maybe everything is now inside an extra folder, I don't know much about how the plugin accesses the resource files.

**Comment by PyvesB** [comment]
In fact the message `[AdvancedAchievements] Failed to get internal item name for advancement icon. Using book instead.` is just noise, it was systematically appearing in Minecraft 1.13 and 1.14 regardless of the value for `AdvancementsBackground`. This is fixed in the commit above.

So, I started on a fresh slate. Using `minecraft:textures/block/sand.png` as the value for `AdvancementsBackground` works flawlessly for me:
![2019-09-08_11 25 55](https://user-images.githubusercontent.com/10694593/64486916-7c290300-d22b-11e9-98d2-230493360634.png)

**Comment by s1h4d0w** [comment]
That is awesome, thanks for the fix! I'll wait for the next build as I'm not very good with compiling myself.

**Comment by PyvesB** [comment]
I'll aim for a deployment sometime in the coming week.
