### ISSUE TITLE
Money Error / -Money wont grow up!

### ISSUE THREAD

**Issue by ManuXzUWM** [PyvesB/AdvancedAchievements#618]
Hey,

We gave the player an achivements reward by using the following:
`Deaths:
  '10':
    Goal: Don't die 10 Times!
    Message: You have died 10 Times!
    Name: deaths_10
    DisplayName: §7[§fDeath§7] §bDeath Apprentice
    Reward:
      Command:
        Execute: eco take PLAYER 200
        Display: §3You will lose &c10.000$`

Now to player got -10.000$

Next the player got the following Reward:

`  pig:
    '50':
      Goal: Breed 50 Pigs.
      Message: You have bred 50 Pigs!
      Name: breeding_50_pig
      DisplayName: §7[§fBreeder§7] §9Pig Journeyman
      Reward:
        Money: 350`

And nothing changed so he is still at -10.000$.
The function is working very fine if the player has 0$+.
Any solution?

Best Regards

Unitedworldminers Team

**Comment by supertassu** [comment]
Hi. What economy plugin are you using?

**Comment by ManuXzUWM** [comment]
We are using the Plugin Vault

**Comment by toguno** [comment]
We are also having this issue, we are using essentialseco. Originally we had an issue where upon disconnect essentials generated a new userdata file for any user with capital letters. After some experimenting, we found that after removing Advanced Achievements the issue was resolved. We tried to install older versions of the plugin to see if that remedied the issue, yet it persisted. One of the symptoms of this issue is that players with capital letters money was displayed when doing /money, but could not be affected by any other plugin. We used mycommand to confirm this bug, making a command called "/montest" which displayed a users money. Essentials /money would print the proper amount of money, but /montest would print $0. What we noticed specifically: for users with capital letters in their name something is not working properly and the issue only occurs when advanced achievements is installed. While installed, a new userdata file was created for users under a different uuid and within those files, labeled them as bots. Essentials then bugged out making users unable to modify their balance, while /money still displayed their balance.

Server version: Paper-31, MC 1.15.1
Bungeecord version: 
Plugins: Waterfall-309 MC 1.15.1
AdvancedAchievements, AdvancedModreq, ChestShop, ChestShopNotifier*, ColoredSigns*, CoreProtect, DisableJoinMessage*, dynmap*, Essentials, EssentialsSpawn, Lottery, LWC, Multiverse-Core, Multiverse-NetherPortals, Multiverse-Portals, MyCommand, PermissionsEx*, Plan, Vault, WorldBorder, WorldEdit, WorldEditCUI, WorldGuard

**Comment by PyvesB** [comment]
I just tested things with a Spigot 1.15 server containing the latest versions of Advanced Achievements (5.13.2), Vault (1.7.2) and EssentialsX (2.17.1), `Money` rewards work as expected. Note that no other plugins are installed and the server's settings are pretty close to the default setup.

Please make sure you are also using the latest versions of the aforementioned plugins. If you are still having issues, please provide a minimal server setup to easily reproduce the issue. 😉

**Comment by ManuXzUWM** [comment]
Thanks for this info. We are currently setting up a 1.15.x server. We will reply if it works or not ;) .

**Comment by PyvesB** [comment]
@ManuXzUWM how's the setup going?
