### ISSUE TITLE
Performance decrease with block breaks

### ISSUE THREAD

**Issue by haloflooder** [PyvesB/AdvancedAchievements#625]
On certain type of servers. AACH's block break listener will decrease the server's performance when AACH is used with other plugins that manually fires the block break event for custom enchants.

With only 1 player, it causes around a 7% decrease with a single player mining with a custom enchant.
![spark profiler](https://i.imgur.com/yr0p9lG.png)

We currently have a patch added to our achievement addon to cache the block breaks for aach and process the cache every 5 seconds to increase the stats manually.

**Comment by PyvesB** [comment]
Hi @haloflooder,

To be honest, this is confusing and lacks quite a lot of detail.

What do you mean by "On certain type of servers."? What do you mean by "other plugins that manually fires the block break event"? Do they not use the Bukkit event API capabilities? I'm unsure how custom enchants could impact performance as the same code is run in Advanced Achievements for all break events.

What does that screenshot represent and what do the percentages mean? What period of time does it cover? Was it run once the server had already been running with several players for some time, to ensure that the JIT compiler had had a chance to kick in?

Even plain Java string, stream and collection operations are displayed with high percentages, so I'm guessing this is either not JIT-compiled and/or it's run on a very old Java VM and/or the server is underpowered/misconfigured.

Please provide some details and some actionable observations. 😉

**Comment by virustotalop** [comment]
Hi @PyvesB ,
I work with @haloflooder and I wrote the custom enchants plugin that he is referencing. The enchants plugin fires off a block break event for every block that is broken so that it can be caught by protection plugins I.E WorldGuard etc. Due to the nature of the amount of block breaks running sometimes hundreds of thousands to millions block break events a minute are running so we have had to cache a lot of data, which seems like that is not being done here. I know we are not the normal use case for this plugin and if you need any additional information or testing etc I would be more than happy to help. Also for reference we are running one of the latest versions of jdk8. The server had quite some uptime by that point so it shouldn't be an issue of the vm not warming up etc. The percentages given were from [spark.](https://github.com/lucko/spark) Attached below is a more expanded version of the profile given above.

![profile](https://i.imgur.com/70YQP1E.png)

**Comment by PyvesB** [comment]
I've had a go at optimising part of the code path picked up by the profiler. 
I'm not expecting a major performance boost, but it _should_ smooth things a bit. Here's a test version if you want to give it a go:
[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/3964935/AdvancedAchievements.zip)

I would suggest trying out a more modern JDK: Java 8 was initially released almost 6 years ago, Oracle generally doesn't do much on the performance side in subsequent patch releases. Java 11 or 13 would be better options nowadays. You may also want to look at the [OpenJ9](https://github.com/eclipse/openj9) VM. 😉
