### ISSUE TITLE
Inventory Full

### ISSUE THREAD

**Issue by KlayaR** [PyvesB/AdvancedAchievements#720]
Hello
I have a lot a players complaining about not receiving their rewards because of full inventory, and I guess its their fault. But is there a way to drop the items next to them or to have them collect their rewards in the menu?
Thank you

**Comment by PyvesB** [comment]
Hello @KlayaR ,

If a player's inventory is full, `Item` rewards will be dropped on the ground at their location (see [this bit of code](https://github.com/PyvesB/AdvancedAchievements/blob/1a2fa58a97efa869511bb88ee9bfadf76096c4b6/advanced-achievements-plugin/src/main/java/com/hm/achievement/listener/PlayerAdvancedAchievementListener.java#L256). This has been the case since the very early days of the plugin. Make sure there aren't any other plugins or server configurations that are preventing the drop, and that it's not just a case of players not noticing that the items were dropped next to them. :wink:

**Comment by JHarris12345** [comment]
@PyvesB Im gonna use this thread to sort this then because you linked your code but I can tell you that code wont work for checking if the inventory is full because that method checks armor slots too. So if a player is not wearing armor and completes a quest, it will tell the plugin that their inventory is not full when in reality it is. I have a method for checking if an inv is empty if you wish to replace it and fix this issue:

`    public static Integer CheckFreeSlots (Player player) {
        Integer freeSlots = 0;
        Integer totalSlots = 36;
        if (player.getInventory().getItemInOffHand().getType() != Material.AIR) totalSlots = totalSlots + 1;
        if (player.getInventory().getHelmet() != null) totalSlots = totalSlots + 1;
        if (player.getInventory().getChestplate() != null) totalSlots = totalSlots + 1;
        if (player.getInventory().getBoots() != null) totalSlots = totalSlots + 1;
        if (player.getInventory().getLeggings() != null) totalSlots = totalSlots + 1;

        for (ItemStack i : player.getInventory().getContents()) {
            if (i == null) continue;
            freeSlots++;
        }
        freeSlots = totalSlots - freeSlots;
        return freeSlots;
    }`

**Comment by PyvesB** [comment]
@JHarris12345 okay thanks, that's some very useful information. 👍🏻 The code probably works fine on older Minecraft versions where armors don't yet exist, and I simply must never have tested this specific functionality with a more recent server version.

Thanks for sharing some code. I'll see if I can come up with something simpler, because what you shared will break compatibility with older server versions and will stop working properly if new special inventory slots are introduced.

**Comment by JHarris12345** [comment]
No worries. But yeah the remember that the getContents and getNextSlot methods include the 4 armor slots AND the off hand. So your method has to take into account the 5 special slots, not just the armor
