### ISSUE TITLE
Stacking

### ISSUE THREAD

**Issue by koloseum123** [PyvesB/AdvancedAchievements#728]
Hello, I have a question how to arrange these achievements horizontally so that they look nicer, I tried to set, but I do not know how I ask you, can anyone know?

I mean putting these achievements horizontally in the GUI

**Comment by PyvesB** [comment]
Hello @koloseum123, you can modify the position of achievement categories by modifying their order in _gui.yml_. Same goes for subcategories in _config.yml_. : wink:

**Comment by PyvesB** [comment]
Hello @koloseum123, you can modify the position of achievement categories by modifying their order in _gui.yml_. Same goes for subcategories in _config.yml_. : wink:

**Comment by koloseum123** [comment]
Will you give an example of how to do this? I will be very grateful

**Comment by PyvesB** [comment]
Well for example in _gui.yml_, switch
````
Places:
  Item: stone
Breaks:
  Item: stone_bricks
````
to
````
Breaks:
  Item: stone_bricks
Places:
  Item: stone
````

And in _config.yml_ switch
````
TargetsShot:
  villager:
    10:
      Goal: Throw things at villagers.
      Message: You lapidated villagers 10 times.
      Name: targetsshot_10_villager
      DisplayName: The Stoner
  glass:
    100:
      Goal: Try to break granny's windows.
      Message: You shot 100 projectiles at glass blocks!
      Name: targetsshot_100_glass
      DisplayName: Window Breaker
````
to
````
TargetsShot:
  glass:
    100:
      Goal: Try to break granny's windows.
      Message: You shot 100 projectiles at glass blocks!
      Name: targetsshot_100_glass
      DisplayName: Window Breaker
  villager:
    10:
      Goal: Throw things at villagers.
      Message: You lapidated villagers 10 times.
      Name: targetsshot_10_villager
      DisplayName: The Stoner
````

**Comment by koloseum123** [comment]
Unfortunately it still doesn't work, I did as you wrote and the same achievements are vertically

**Comment by PyvesB** [comment]
I'm really unsure what you're actually trying to achieve at this point.

**Comment by koloseum123** [comment]
Just the way you write, I do it like you and none of it, they all continue to display vertically instead of horizontally

**Comment by PyvesB** [comment]
Please provide a screenshot explaining what you're trying to achieve.

**Comment by koloseum123** [comment]
Now they are like this:
https://prnt.sc/sd4gam

And I want them to be like this:
https://prnt.sc/sd4fxk

**Comment by PyvesB** [comment]
Okay, so you were talking about the native Minecraft GUI with advancements rather than Advanced Achievements GUI with achievements. This was misleading.

Does Minecraft support displaying things horizontally rather than vertically, i.e. do you have examples of other advancement pages that are displayed in that way?

**Comment by koloseum123** [comment]
They are so vertically, one arranged under the hostile:
https://prnt.sc/sdegbq
And I want them to be sorted from left to right.

**Comment by PyvesB** [comment]
> Does Minecraft support displaying things horizontally rather than vertically, i.e. do you have examples of other advancement pages that are displayed in that way?

You did not answer this question. I had a look myself, and the other built-in advancement panels also follow the same left to right flow as Advanced Achievements, i.e. advancements for a given series appear in consecutive columns rather than rows as you're requesting. This behaviour is also documented in [Gamepedia](https://minecraft.gamepedia.com/Advancements/JSON_format#Position):

> The game automatically arranges advancements [...] The root advancement appears on the leftmost column while each arrow points to an advancement in the next column.

Unfortunately there's nothing I can do to change this behaviour in Advanced Achievements. You could try to open a feature request in [Minecraft's issue tracker](https://bugs.mojang.com/projects/MC/issues), though I'm unsure how likely Mojang are to implement such a feature.
