### ISSUE TITLE
Help me is serious! 

### ISSUE THREAD

**Issue by Junior007dj** [PyvesB/AdvancedAchievements#734]
Hello it's junior007

You have close my issue BUT yes if is not a aach can you help me, because is your plugin say the bugs, not another plugins!!!

Thank if you really help me, or I not happy for the support, and review! 
Closed issus #731

**Comment by PyvesB** [comment]
Hello @Junior007dj,

I closed your previous issue because:
* you did not follow the bug report template that GitHub suggests to use when creating an issue on this repository.
* the sole contents of the issue were a stack trace copy pasted without any context nor explanations.
* the stack trace was not even properly formatted, even though the [contribution guidelines](https://github.com/PyvesB/AdvancedAchievements/blob/master/CONTRIBUTING.md) explain how to do this. Note that a link to the contribution guidelines is automatically displayed by GitHub when you first try to create an issue on a repository, you shouldn't have missed this.
* the stack trace doesn't actually seem complete. Where is actual the log line with the plugin name for example?
* you didn't show any basic courtesy, even though this is kindly reminded in the [contribution guidelines](https://github.com/PyvesB/AdvancedAchievements/blob/master/CONTRIBUTING.md).

Whether it be with Advanced Achievements or any other software project, not many people will be willing to provide _free_ support with such lack of respect and care. Feel free to open a new issue with **all of the above** addressed.
