### ISSUE TITLE
New achievements (jump, treasure, anvil)

### ISSUE THREAD

**Issue by JohOply** [PyvesB/AdvancedAchievements#81]
Hi!

Could you add these achievements categories:
- jump
- treasure fished
- more details with anvil

I read that you are not able to implement new achievements soon, but i prefer put them here :)

Thank you for reading :)

**Comment by PyvesB** [comment]
Hello,

Thanks for the ideas. I am actually able to implement new achievements easily. At first I thought the GUI could only contain 36 spaces, as stated in the Spigot documentation. So adding new categories would have been complicated as I would have had to implement some sort of GUI pagination system. But turns out the documentation is wrong (or I might have simply misread), I can for instance create GUIs containing 99 slots for the achievements listings without any major shortcomings. There are still a few reasons why I am reluctant to add new categories though:
- tedious and not really interesting from a developer's point of view.
- to make things nice in the GUI when using all the categories, I would have to implement 9 new categories at the same time to fill all the lines.
- from the user's point of view more categories means a longer set up time, and potentially not as good performance.

So yeah, the bigger picture here is that I'm currently postponing adding new categories, and instead focusing on improving the current features, fixing bugs, and reinforcing the code basis. But new categories will probably be added at some point in the future! ;-)

Cheers,

Pyves

**Comment by PyvesB** [comment]
Hello,

I have implemented the Treasures achievement category in 1a9acb49020217ed337b43e3c92ed1feb00850ae. It will be available in the next official release. ;-)

As far as your two other suggestions are concerned:
- Jump: I've given it some thought, but there is not straightforward way to check this with the current API. Each time a player moves, I would have to check whether his vertical position has increased enough or not. This is definitely not very handy, and climbing a ladder would for instance be considered as jumping. Besides, the load on the server CPU could be quite high.
- More details with anvil: this would require a change to the database structure, which is not a very convenient operation especially with SQLite. This will also not accommodate all users, some will prefer having just the global statistic.

Cheers,

Pyves
