### ISSUE TITLE
Ach dont work.

### ISSUE THREAD

**Issue by DutchUser** [PyvesB/AdvancedAchievements#84]
I found an bug i think. Players cant unloack "Dark Oak Cutter" (default ach)

I tested myself and found out that its not working. Also something else where i place an ? to.

I checked the config and found "RestrictCreative:" default to "false" but why ist default false? Witch creative server will let this to false at all? Can not maybe set it default to true?

**Comment by PyvesB** [comment]
Hello,

There is some confusion in the naming, it in fact corresponds to spruce wood facing up/down ([see here](http://minecraft.gamepedia.com/Wood)). I will modify the naming accordingly.

The default is false because there are very few full creative servers, but on the other hand many more servers which have limited creative zones, some maps in creative, building events in creative mode, ranks that allow to get temporary creative access, etc. All these servers would not want their players to be able to go and extensively farm achievements when switching to creative mode. Even for the rare full creative servers, this plugin is not very interesting as most achievements can easily be abused. The default will stay to false, anyway it's only 5 characters to change for the tiny minority of users which will want to change it. ;-)

Cheers,

Pyves
