### ISSUE TITLE
Issue with the config.yml - adding new achievements

### ISSUE THREAD

**Issue by Loonyy** [PyvesB/AdvancedAchievements#91]
Hey, I'm trying to add more achievements in the config.yml but when I do it seems to break the plugin?
```
# When a player connects during the day.
Connections:
  '1':
    Message: You connected to our server for the first time!
    Name: connect_1
    DisplayName: Good Choice
  ’10’:
    Message: You connected to our server for the tenth time!
    Name: connect_10
    DisplayName: So you like it here?
  '100’:
    Message: You connected to our server for the 100th time!
    Name: connect_100
    DisplayName: Welcome back, friend.
  '1000’:
    Message: You connected to our server for the 1000th time!
    Name: connect_1000
    DisplayName: Thank you.
```
Also, when trying to add rewards to achievements such as the ones above, that seems to not work?

**Comment by Platinteufel** [comment]
Be sure that your .yml is formatted correctly.
http://yaml-online-parser.appspot.com

Otherwise you can upload your config and I will take a short look into it. :)

**Comment by Loonyy** [comment]
I checked if the yaml is fine and it says that it isn't, but I don't understand why? I'm just using the same sample

**Comment by Platinteufel** [comment]
There are some points where you used ` instead of ' (shift+#)

Here's the fixed config:

`#==============================O==============================#
# I---------------------------------------------------------I #
# |    Advanced Achievements 3.0.5 configuration - Readme   | #
# 1---------------------------------------------------------1 #
#==============================o==============================#

# You can use Minecraft chat colors in Message|DisplayName|Goal, but include '' around the whole text: '&4Color'.
# When using colours, you must also double apostrophes: '&2I''ve doubled apostrophes!'.
# Only spaces, no tabs. Don't forget the indents, plugin won't work otherwise!
# To check your file, use: yaml-online-parser.appspot.com
# Do NOT delete any main achievement sections in the configuration file.
# Possible items for rewards/Crafts/Places/Breaks: hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
# Possible mobs for the Kills section:    hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
# Default config.yml file:  github.com/PyvesB/AdvancedAchievements/blob/master/src/main/resources/config.yml
# Visit the wiki for some additional documentation: github.com/PyvesB/AdvancedAchievements/wiki

#=============================O=O=============================#
# II-------------------------------------------------------II #
# |                    General  settings                    | #
# 2---------------------------------------------------------2 #
#=============================o=o=============================#

# Time in seconds between each /aach book.
TimeBook: 500

# Time in seconds between each /aach list.
TimeList: 0

# Check for update on plugin launch and notify when an OP joins the game.
CheckForUpdate: true

# Set to true to activate firework effects when a player receives an achievement.
Firework: true

# Choose BALL_LARGE, BALL, BURST, CREEPER or STAR.
FireworkStyle: BALL_LARGE

# Number of players displayed in /aach top, week and month commands.
TopList: 5

# Set to true to activate particle effects when receiving book and for players in top list.
AdditionalEffects: true

# Set to true to activate sound effects when receiving book and for players in top list.
Sound: true

# Set the icon of the plugin (default: shamrock, '\u2618').
Icon: '\u2618'

# Set the color of the plugin (default: 5, dark purple).
Color: '5'

# Notify other connected players when an achievement is received.
ChatNotify: false

# Separator between name, description and date on a book page.
BookSeparator: ''

# Set the format of the achievement name in /aach list (default: '%ICON% %NAME% %ICON%').
ListAchievementFormat: '%ICON% %NAME% %ICON%'

# Stop stats from increasing when player in creative mode (except Connections and PlayedTime).
RestrictCreative: false

# Stop stats from increasing when player in a specific world (delete the [] before using).
ExcludedWorlds: 
  - arena
  - plotme
  - herobend

# Ignore vertical dimension (Y axis) when calculating distance statistics.
IgnoreVerticalDistance: false

# Don't show these categories in the achievement GUI or in the stats output (delete the [] before using).
# Also prevent obtaining achievements for these categories and prevent stats from increasing.
# If changed, do a full server reload, and not just /aach reload.
DisabledCategories: []
#  - Beds
#  - ItemBreaks
#  - Crafts

# Obfuscate achievements that have not yet been received in /aach list.
ObfuscateNotReceived: false

# Obfuscate progressive achievements:
# For categories with a series of related achievements where the only thing changing is the number of times
# the event has occurred, show achievements that have been obtained and show the next obtainable achievement,
# but obfuscate the additional achievements. In order for this to work properly, achievements must be sorted
# in order of increasing difficulty. For example, under Places, stone, the first achievement could have a
# target of 100 stone,# the second 500 stone, and the third 1000 stone.  When ObfuscateProgressiveAchievements
# is true, initially only the 100 stone achievement will be readable in the GUI.  Once 100 stone have been placed,
# the 500 stone achievement will become legible.
ObfuscateProgressiveAchievements: false

# Hide categories with no achievements yet received in /aach list.
HideNotReceivedCategories: false

# Hide the reward display in /aach list.
HideRewardDisplayInList: false

# Display achievement name and description as screen titles.
TitleScreen: true

# Sort pages of the book in chronological order (false for reverse chronological order).
BookChronologicalOrder: true

# Do not take into account items broken with Silk Touch for the Breaks achievements.
DisableSilkTouchBreaks: false

# Do not take into account ores broken with Silk Touch for the Breaks achievements.
# DisableSilkTouchBreaks takes precedence over this. Not applicable to iron or gold ores.
DisableSilkTouchOreBreaks: false

# Name of the language file.
LanguageFileName: 'lang.yml'

#=============================OOO=============================#
# III-----------------------------------------------------III #
# |                    Database settings                    | #
# 3---------------------------------------------------------3 #
#=============================ooo=============================#

# Make a daily backup of your local database (if sqlite).
DatabaseBackup: true

# Database type, sqlite, postgresql or mysql. Do a full server reload or restart to make this effective.
DatabaseType: sqlite

# Prefix added to the tables in the database. If you switch from the default tables names (no prefix),
# the plugin will attempt an automatic renaming. Otherwise you have to rename your tables manually.
# Do a full server reload or restart to make this effective.
TablePrefix: ''

# Settings to link with MySQL database (ignore if sqlite or postgresql).
MYSQL:
  Database: 'jdbc:mysql://localhost:3306/minecraft'
  User: root
  Password: root

# Settings to link with PostgresSQL database (ignore if sqlite or mysql).
POSTGRESQL:
  Database: 'jdbc:postgresql://localhost:5432/minecraft'
  User: root
  Password: root

#============================OO=OO============================#
# IV-------------------------------------------------------IV #
# |                  Performance settings                   | #
# 4---------------------------------------------------------4 #
#============================oo=oo============================#

# DO NOT CHANGE THE FOLLOWING UNLESS YOU ARE AN EXPERIENCED USER. The intervals are in seconds. 
# If any of the performance settings are changed, do a full server reload, and not just /aach reload.
# Frequency of play time checks for players. Smaller values give more precision but more CPU usage.
PlaytimeTaskInterval: 150

# Calculates distance traveled by players. Smaller values give more precision but more CPU usage.
DistanceTaskInterval: 5

# Frequency of some statistics writes to the database.
PooledRequestsTaskInterval: 60

# Enable multithreading for database write operations.
AsyncPooledRequestsSender: true

#============================OOOOO============================#
# V---------------------------------------------------------V #
# |                  Action  achievements                   | #
# 5---------------------------------------------------------5 #
#============================ooooo============================#

# When a player connects during the day.
Connections:
  '1':
    Message: You connected to our server for the first time!
    Name: connect_1
    DisplayName: Good Choice
  '10':
    Message: You connected to our server for the tenth time!
    Name: connect_10
    DisplayName: So you like it here?
  '100':
    Message: You connected to our server for the 100th time!
    Name: connect_100
    DisplayName: Welcome back, friend.
  '1000':
    Message: You connected to our server for the 1000th time!
    Name: connect_1000
    DisplayName: Thank you.

# When a specific block is placed (specify material name, lower case).
Places:  
  smooth_brick:
    '500':
      # Used in /aach list when achievement not yet received.
      Goal: 'Place 500 stone bricks.'
      # Description; displayed when receiving achievement, and in /aach book and /aach list.
      Message: '&4You have placed 500 stone bricks!'
      # Database name, must also be used in /aach delete and /aach check.
      Name: place_500_smooth_brick
      # Name; displayed when receiving achievement, and in /aach book and /aach list.
      DisplayName: 'Stone Brick Layer'
    '2500':
      Goal: 'Place 2500 stone bricks.'
      Message: '&4You have placed 2500 stone bricks!'
      Name: place_2500_smooth_brick
      DisplayName: 'Stone Brick Architect'
  stone:
    '100':
      Message: '&4One hundred placed stones!'
      Name: place_100_stone
      DisplayName: Stone Addict
    '1000':
      Message: '&4One thousand placed stones!'
      Name: place_1000_stone
      DisplayName: Stone God

# When a specific block is broken (specify material name, lower case).
# Below, the notation log:1 means log item with metadata 1.
Breaks: 
  log:1:
    '100':
      Message: '&2You have cut dark oak 100 logs!'
      Name: break_1_log1
      DisplayName: Dark Oak Cutter
  stone:
    '1':
      Message: '&1The first time you went mining!'
      Name: break_1_stone
      DisplayName: Cobble!
      # Use semicolons for multiple command rewards. PLAYER will be replaced by player's name.
      Reward:
        Command: give PLAYER 158 10; give PLAYER 126 5

# When a specific mob is killed (specify an entity name or poweredcreeper or player, lower case).
Kills:
  zombie:
    '1':
      Message: '&8The first time you killed a zombie!'
      DisplayName: The Walking Dead
      Name: kills_1_zombie
      Reward:
        Money: 10         
        Item: diamond 1

# When a specific item is crafted (specify material name, lower case).
Crafts:
  diamond_sword:
    '1':
      Message: The first time you crafted a blade!
      Name: craft_1_blade
      DisplayName: Blacksmith Apprentice
      Reward:
        Money: 2

# When the player dies.
Deaths:
  '1':
    Message: The first time you died!
    Name: deaths_1
    DisplayName: Rest in Peace

# When an arrow is shot.
Arrows:
  '50':
    Message: '50 arrows shot!'
    Name: arrows_50
    DisplayName: Arrows Around the Place

# When a snowball is thrown.  
Snowballs:
  '1000':
    Message: '1000 snowballs thrown. That''s the spirit!'
    Name: snowballs_1000
    DisplayName: Winter Addict 

# When an egg is thrown.  
Eggs:
  '1000':
    Message: '1000 eggs thrown!'
    Name: eggs_1000
    DisplayName: Omelet Addict 

# When a fish is caught. 
Fish:
  '1':
    Message: The first time you caught a fish!
    Name: fish_1
    DisplayName: Time for Fish and Chips

# When a tool/armor/weapon is broken.  
ItemBreaks:
  '1':
    Message: You broke your favorite tool!
    Name: itembreaks_1
    DisplayName: '&4Clumsy Guy'

# When an item is eaten (excludes potions and milk).
EatenItems:
  '1':
    Message: Just had a snack!
    Name: eatenitems_1
    DisplayName: First Snack  

# When a sheep is sheared.
Shear:
  '100':
    Message: 100 sheep sheared!
    Name: shear_100
    DisplayName: '&1Wool Addict'

# When a cow is milked.
Milk:
  '1':
    Message: Just milked a cow!
    Name: milk_1
    DisplayName: First Milk    

# When a trade with a villager is made.
Trades:
  '1':
    Message: Doing business with your first villager!
    Name: trades_1
    DisplayName: First Trade    

# When an anvil is used.
AnvilsUsed:
  '1':
    Message: You just repaired your first item!
    Name: anvilsused_1
    DisplayName: First Repair 

# When an enchantment is performed.
Enchantments:
  '5':
    Message: 5 objects enchanted!
    Name: enchantments_5
    DisplayName: '&5Wizard'

# When a bed is entered. 
Beds:  
  '5':
    Message: You entered a bed 5 times!
    Name: bed_5
    DisplayName: Sleepy guy 

# Maximum level reached.    
MaxLevel:  
  '10':
    Message: Level 10 reached!
    Name: maxlevel_10
    DisplayName: '&4Rookie'  

# When a potion is consumed.
ConsumedPotions:
  '100':
    Message: Drinking weird beverages all the time...
    Name: consumedpotions_100
    DisplayName: Alcoholic 

# Amount of time played on the server (in hours, use integers).
PlayedTime:
  '1':
    Message: You played for one hour on the server!
    Name: playedtime_1
    DisplayName: First Hour
  '10':
    Message: You played for ten hours on the server!
    Name: playedtime_10
    DisplayName: Tenth Hour
  '50':
    Message: You played for fifty hours on the server!
    Name: playedtime_50
    DisplayName: Go hard or go home.
  '100':
    Message: You played during 100 hours on the server!
    Name: playedtime_100
    DisplayName: The very best...
  '1000':
    Message: You played for 1000 hours! Thank you!
    Name: playedtime_1000
    DisplayName: Legendary Player

# When a distance is traveled by foot.
DistanceFoot:
  '1000':
    Message: You traveled 1000 blocks by foot!
    Name: distancefoot_1000
    DisplayName: Big Walker 

# When a distance is traveled on a pig.
DistancePig:
  '100':
    Message: You traveled 100 blocks on a pig!
    Name: distancepig_100
    DisplayName: Carrot on a Stick Master

# When a distance is traveled on a horse.
DistanceHorse:
  '500':
    Message: You traveled 500 blocks on a horse!
    Name: distancehorse_500
    DisplayName: The Avener

# When a distance is traveled in a minecart.
DistanceMinecart:
  '100':
    Message: You traveled 100 blocks in a minecart!
    Name: distanceminecart_100
    DisplayName: Carting Fan

# When a distance is traveled in a boat.
DistanceBoat:
  '200':
    Message: You traveled 200 blocks in a boat!
    Name: distanceboat_200
    DisplayName: Great Sailor

# When a distance is traveled with elytra.
# (ignored on Minecraft versions prior to 1.9)
DistanceGliding:
  '100':
    Message: You traveled 100 blocks with elytra!
    Name: distancegliding_100
    DisplayName: Angel

# When an item is dropped on the ground.
ItemDrops:
  '15':
    Message: You're killing the planet!
    Name: itemdrops_15
    DisplayName: Polluter

# When soil is plowed with a hoe.
HoePlowings:
  '10':
    Message: You plowed the ground 10 times!
    Name: hoeplowings_10
    DisplayName: Farmer
    Reward:                 
        Item: cookie 15

# When bone meal is used to fertilise plants.
Fertilising:
  '15':
    Message: You used bone meal on plants 15 times!
    Name: fertilising_15
    DisplayName: Gardener

# When an animal is tamed.
Taming:
  '1':
    Message: You tamed your first animal!
    Name: taming_1
    DisplayName: Tamer

# When a potion is brewed.
Brewing:
  '1':
    Message: You brewed your first potion!
    Name: brewing_1
    DisplayName: Alchemist

# When a firework is launched.
Fireworks:
  '10':
    Message: You launched 10 fireworks!
    Name: fireworks_10
    DisplayName: Pyrotechnist

# When a music disc is played.
MusicDiscs:
  '1':
    Message: One jukebox used!
    Name: musicdiscs_1
    DisplayName: DJ

# When a player teleports with an enderpearl.
EnderPearls:
  '10':
    Message: 10 teleportations with ender pearls!
    Name: enderpearls_10
    DisplayName: Teleport Man

#===========================OOO=OOO===========================#
# VI-------------------------------------------------------VI #
# |                  Command achievements                   | #
# 6---------------------------------------------------------6 #
#===========================ooo=ooo===========================#

# Let achievement commands be given several times.
MultiCommand: true

# A player with achievement.give (or the console) can use /aach give yourAch1 PLAYER to give
# yourAch1 achievement to PLAYER. The /aach give command does NOT work with other achievements.
Commands:
  yourAch1:
    Message: You took part in the special event!
    Name: yourAch1
    DisplayName: Special Event Achievement!

#===========================OOOOOOO===========================#
# VII-----------------------------------------------------VII #
# |         Parameters to appear in future versions         | #
# 7---------------------------------------------------------7 #
#===========================ooooooo===========================#`

**Comment by Loonyy** [comment]
Do you mind editing that, highlighting it all and clicking the code button(<>)?

**Comment by Loonyy** [comment]
Infact I can just edit the changes myself, thank you!

Second question - can you add rewards to ALL achievements?

**Comment by Platinteufel** [comment]
Sure. Here you go:

```
# When a player connects during the day.
Connections:
  '1':
    Message: You connected to our server for the first time!
    Name: connect_1
    DisplayName: Good Choice
    **Reward:
      Money: 30
      Item: diamond 10
      Command: pex promote PLAYER**
  ’10’:
    Message: You connected to our server for the tenth time!
    Name: connect_10
    DisplayName: So you like it here?
    **Reward:
      Money: 50
      Item: emerald 30
      Command: pex user PLAYER add essentials.fly**
```

**Comment by Loonyy** [comment]
Thanks a lot!

**Comment by PyvesB** [comment]
Hello,

Thank you for you help Platinteufel. ;-)

Are you still having any issues Loonyy? 

Cheers,

Pyves
