### ISSUE TITLE
CB/Spigot 1.11

### ISSUE THREAD

**Issue by Platinteufel** [PyvesB/AdvancedAchievements#98]
Hey @PyvesB,

please don't forget to compile/test future versions also against CB/Spigot 1.11. ;-)

https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-1-11-released.193887/
https://www.spigotmc.org/threads/bukkit-1-11-api-draft.193437/

**Comment by PyvesB** [comment]
Hello,

Yep, I updated my local version as soon as I saw the official Spigot announcement. 

Please tell me if you see any bugs with Minecraft 1.11; so far I know fireworks don't work, but I think that is a mistake on Spigot's end, not on mine. ;-)

Cheers,

Pyves

**Comment by Platinteufel** [comment]
Well, as far as I know there's currently a problem with a lot of plugins that are using SQLite because of the SQLite update from 3.7.x to 3.15.x, but I will also test it asap. ;-)

**Comment by PyvesB** [comment]
I didn't notice any problems with SQLite after a few quick tests. PostgreSQL should also still be working fine as the drivers are not directly included in Spigot. As far as MySQL is concerned, I'll do some quick testing this week-end.

My current plan is to push development forward in order to finish the global refactoring of the plugin, and add a few new features, as well as 9 new categories. A lot of work ahead, but I do want to get it tackled in the next few days. Any help I will get for testing will be welcome! ;-)

**Comment by Platinteufel** [comment]
Sure, if you could compile a jar I'm pleased to test new features and compatibility with 1.11. :)

**Comment by PyvesB** [comment]
Hello,

Here is a first Beta for the future version 4.0 of the plugin. Please open new tickets if you find any issues, and leave this one for more general feedback. ;-)

[AdvancedAchievements-3.0.5.zip](https://github.com/PyvesB/AdvancedAchievements/files/610190/AdvancedAchievements-3.0.5.zip)

Cheers,

Pyves

**Comment by PyvesB** [comment]
Hello,

Here is a more stable version which fixes many bugs:

[AdvancedAchievements-3.0.5.zip](https://github.com/PyvesB/AdvancedAchievements/files/612241/AdvancedAchievements-3.0.5.zip)

Cheers,

Pyves

**Comment by Platinteufel** [comment]
Hey, I'll test it as soon as possible. :)

The first thing I've noticed is that the new categories appear in the "Parameters to appear in future versions" category after upgrading my testserver. For more specific issues I will create new tickets. ;-)

![unbenannt](https://cloud.githubusercontent.com/assets/13700636/20610604/329448d2-b29c-11e6-92e9-c4b544e87728.PNG)


Cheers ;-)

**Comment by Platinteufel** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/13700636/20610891/0ddeb98c-b2a1-11e6-9b51-f0c812234091.PNG)

Somes spaces would be nice here. :)

**Comment by PyvesB** [comment]
Thank you for your feedback!

I will take care of the space for PlayedTime, it should be the same as elsewhere.

Well yeah, that's the point of the "Parameters to appear in future versions" section, when you upgrade to a new version parameters are added at the end of the file. It would be really complicated to insert everything at the right place when upgrading the configuration file. ;-)

When new categories are added, they are also put in the DisabledCategories list, so that user can safely add his achievements to the configuration file while they are disabled. You must implement the achievements for the new categories, remove the category names from the disabled list and do a FULL server reload (only doing an /aach reload will lead to exceptions).

**Comment by Platinteufel** [comment]
Well, after enabling the `Smelting` category and restarting the server I recieve this error after typing /aach list: http://pastebin.com/hgZhKcpJ
I've double checked that there's no syntax error in config.
Also other categories throwing those errors after enabling them.

Please also take care to the typo in `DistanceLama` (red cirlce in the screenshot above). ;-)

**Comment by PyvesB** [comment]
Hello,

I have attempted a fix, could you please tell me whether it works? If not, could you send me your configuration file?

[AdvancedAchievements-3.0.5.zip](https://github.com/PyvesB/AdvancedAchievements/files/613772/AdvancedAchievements-3.0.5.zip)


This is not a typo, [llama is spelt like this in English](https://en.oxforddictionaries.com/definition/llama) (probably due to the Spanish origins of the word). ;-)  

Cheers,

Pyves

**Comment by Platinteufel** [comment]
Oh okay, sorry. "Llama" looks weird for me since it's only "Lama" in German. ;-)

After some short tests I opened some tickets. I haven't tested this special PetMaster achievements. 

Cheers ;-)

**Comment by PyvesB** [comment]
Releasing version 4.0 of the plugin, everything seems to be working fine, and having hundreds of servers upgrading will enable to spot the remaining issues if there are any. Thank you for your help in testing!

Cheers,

Pyves
