### ISSUE TITLE
3.5 Beta - /aach book

### ISSUE THREAD

**Issue by Platinteufel** [PyvesB/AdvancedAchievements#99]
/aach book doesn't work in the latest beta version with Spigot 1.10.2.
http://pastebin.com/WActbbv4
Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.Sound.LEVEL_UP

Haven't tested it in 1.11 yet.

**Comment by Platinteufel** [comment]
Same with Spigot 1.11.

**Comment by Platinteufel** [comment]
The same with /aach top, /aach week, /aach month, ..
http://pastebin.com/1AwkyEhm
Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.Sound.FIREWORK_BLAST

Maybe it works with `ENTITY_FIREWORK_BLAST`?
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html#ENTITY_FIREWORK_BLAST

**Comment by PyvesB** [comment]
Hello,

My bad, I was recently working with a library that had a custom function that would return null if a the enum was not found, and I got confused by thinking _valueOf_ would do the same. Never caught this behaviour as I in general test with Minecraft 1.8.9. Will be fixed in a minute. ;-)

Cheers,

Pyves
